### ISSUE TITLE
DenoiseSharpen in other apps

### ISSUE THREAD

**Issue by CameraRick** [NatronGitHub/openfx-misc#46]
Hi there,

I love DenoiseSharpen and I'm quite interested to use it in different apps, too.
So far I was able to copy the Misc.ofx bundled from Natron to make it work. For now I only tried it in Resolve (I have no other OFX-using Software except Resolve and Natron here, at work I'll test in Nuke), but had some issues and doesn't really work, unfortunately :( 

I do understand that this is no priority, but I thought I'd still share it, in my eyes this greatly help the popularity :) 
I'll list the things I noticed.

**- denoise doesn't work**
Ok that's the biggest one ... :) the denoise doesn't work. Even when the region locks (so the analysis "worked" (see below)) it doesn't denoise at all. Outputting Noise only will give a 100% black image. Changing values doesn't do anything. Doesn't matter if you are on YCbCr or RGB etc

**- analysis doesn't always seem to work**
Usually it should lock the region etc when you hit the button, but that doesn't always work, even when pressed repeatedly.

**- default analysis-box is at 0:0 with a size of 1:1**
The default position is the same as in Natron, but the size is not the input, it's 1 for each axis. This is no big issue, as you can type a bigger size and go from the (just grabbing is a bit hard because of the small preview window in Resolve)

The Sharpen function works flawless, no issue here.
My guess is that the analysis doesn't properly work, why ever that is.
For testing, I just applied the effect to a Serial Node, as you'd normally do it with OFX plugins.

I used the Misc.ofx.bundle from Natron 2.2.3 in DaVinci Resolve Studio 12.5.4
I'm on Windows 10 Pro

**Comment by devernay** [comment]
I may test it one of these days, but Resolve is a PITA with regards to OpenFX development:

- no possibility to use a debugger - they block totally the debugger, contrary to Nuke
- the *only* way to debug is printf()

Besides, Resolve is *very* slow to execute CPU-based OpenFX plugins, because they always render the full frame at full resolution, and don't support multithreading at all.

BTW, Natron 2.2.4 is now compatible with effects developed with the Resolve OpenFX SDK, see https://github.com/baldavenger/Win-OFX

**Comment by CameraRick** [comment]
Hi there,

I got the mail that Natron now supports the other OFX too, pretty neat :) I still have to find a Matrix plugin (not ColorMatrix) somewhere, someone might have made one :)

I already saw that Resolve is really slow with the Plugins, but that's better than nothing! My motivation is to have a good denoise inside Resolve that works for free, unlike the Studio version or NEAT Video. Now I personally own both, Resolve Studio and NEAT, but I think it's still a great addition! :)
Thanks for the clarification on the problematics, and thank you for looking into it :)

**Comment by devernay** [comment]
> I got the mail that Natron now supports the other OFX too, pretty neat :) I still have to find a Matrix plugin (not ColorMatrix) somewhere, someone might have made one :)
> 
> 

what kind of Matrix plugin are you looking for? You mean MatrixTransform? I can do it in a few minutes if that's what you're looking for, but you can also easily use cornerpin (just feed it with the transforms of 0,0 1,0 0,1 1,1)
The question with MatrixTransform is: in what Units should be the transform. For me, it should be in canonical coordinates (0,0 at the bottom-left of the bottom-left pixel)

**Comment by CameraRick** [comment]
I actually don't know how it's called specifically, I only know it as "Matrix", usually 3x3 or 5x5 in size.
Convolution Matrix also seems to be a name for it: https://docs.gimp.org/en/plug-in-convmatrix.html

**Comment by devernay** [comment]
Denoising works for me, but Resolve is really making things hard.
I just fixed the analysisbox issue (which is a Resolve issue, really), and also fixed many plugins:
- all generators (including Radial, Rectangle...)
- CopyRectangle
- DenoiseSharpen
- LensDistortion
- HSVTool
- ImageStatistics
- NoOp
- Position
I noticed that the analysis box sometimes does not appear when the box is unchecked, but really that's just one more Resolve bug.

The worse bug is that it renders an image each time a parameter is changed, even if it's not significant. Consequently, I think I will make a Resolve-specific behavior, where it doesn't denoise at all unless the analysis is locked. Would that be OK for you? It will make the plugin more responsive of course.

Another issue is that Resolve seems to always return "1" as the number of CPUs, and doesn't seem to implement multithreading, resulting in slow rendenring. We can fix that by writing a plugin-side mutithread suite. This will speed up all our effects.

**Comment by CameraRick** [comment]
>>Would that be OK for you?
Absolutely! Would be great.

>>We can fix that by writing a plugin-side mutithread suite. 
That sounds like it isn't done easily, right? I don't want to drag you away from Natron-development, and I totally appreciate that you put time and thoughts into 3rd Party implementation, this is a great helper for everyone :)

**Comment by CameraRick** [comment]
hi there,

I just tested the new misc.ofx from Natron 2.2.5 with Resolve, thanks for taking on this issue!

For now I didn't get a result. I applied the plugin, position the box and hit "analyze". The region locks, and it seems to load, but I still have just the noisy output. When I set the output to "noise", I only get a black image like before (which makes sense, as it's only the noise, which isn't captured)

**Comment by szhorvat** [comment]
Does DenoiseSharpen work in Resolve 14 (free version) on OS X? I tried the misc bundle from Natron 2.3.2, but trying to use this plugin causes Resolve to crash. I also tried compiling (`nomulti`, using `clang-5.0` from MacPorts, with OpenMP), but then Resolve would hang with 100% (multi-core) CPU usage when trying to use the plugin. Other plugins I tried did work.

**Comment by devernay** [comment]
I'll take a look at it when I have time.
@szhorvat Did you use the version from the app store or the downloaded version? I think the app store version could not load OFX plugins, so I wonder if this was fixed.

**Comment by szhorvat** [comment]
I used the downloaded version.  Please do not spend too much time on this just because I asked, though.  I am new to this kind of software and I naïvely assumed that any OpenFX plugin would work in any host.  It seems the situation is not nearly as simple as that, and making plugins work takes a lot of effort ...

**Comment by devernay** [comment]
Analysis does not seem to work on Resolve 14, will try Resolve 15.
Note that https://github.com/NatronGitHub/openfx/commit/1ddffffc088d1376579c3debec7db95079474e41 fixes a crash on Resolve 14.
Also note that the windows binary is now available on https://ci.appveyor.com/project/NatronGitHub/openfx-misc/build/artifacts

**Comment by devernay** [comment]
It may be fixed see  https://github.com/NatronGitHub/openfx-misc/issues/75
@CameraRick  can you please try with recent artifacts from https://ci.appveyor.com/project/NatronGitHub/openfx-misc/build/artifacts ?
If it's still not working, I'll leave this open, else I'll close it.

**Comment by CameraRick** [comment]
Hi there deverney,

still not working as expected :( I recorded a video to show it: https://youtu.be/LVvt7-2q3s4

I also show the behaviour in Fusion stand alone, but we didn't talk about it in this thread. What's weird is that I could've sworn we talked about Fusion as well. So anyway, there it goes! :)

Best,
Lucas

**Comment by devernay** [comment]
Thank you, I can still see some improvements, because the processing now works!
Can you please edit the top message, so that it reflects these:
- it seems like denoise now actually works (you get an output when you adjust the parameters). Does the "Noise" output also work?
- the OpenGL interact manipulation doesn't work in Fusion. This may be because of poor OFX support in Fusion. Do you have other OpenFX plugins with an OpenGL "interact" that work? 
- the OpenGL interact is drawn too small on both Resolve and Fusion - I will add an extra parameter to draw everything larger.
- the Analysis doesn't work in Resolve - I'll try to see what happens on Resolve on macOS

**Comment by devernay** [comment]
The fact that the analysis doesn't work in Resolve is clearly a Resolve bug: I'm calling [clipGetImage](https://openfx.readthedocs.io/en/master/Reference/suites/ofxImageEffectSuiteReference.html#_CPPv4N21OfxImageEffectSuiteV112clipGetImageE) from the [kOfxActionInstanceChanged action](https://openfx.readthedocs.io/en/master/Reference/ofxImageEffectActions.html#c.kOfxActionInstanceChanged), which is where one catches a button press, and the returned image has correct bounds (Resolve always returns the whole image) but contains garbage.

I'm pretty sure it used to work before they merged the Fusion engine in Resolve...

Concerning the Fusion issue, since I don't have a Fusion license and a way to debug it, I can help much.

I added a "HiDPI" checkbox to plugins with interacts, so that they are more usable in highDPI-compatible application (eg Resolve or Nuke).

Use Natron or Nuke to get proper OpenFX support, but don't blame me for the very poor OFX support in Fusion, Resolve and Vegas. We already implemented lots of workarounds, but here there's nothing I can do to get the input image in Resolve.

**Comment by CameraRick** [comment]
Hi Frederic,

you did your best, thanks so much for looking into it for such a long time. You can't have it all :)

For what it's worth, if you have a Resolve Studio license, Fusion standalone will start with that as well (at least with the Dongle)
