### ISSUE TITLE
Request Commercial License

### ISSUE THREAD

**Issue by WindowsNT** [NatronGitHub/openfx-misc#77]
Hello.
What would be the new license  requirements to include the precompiled binaries with my commercial project?
Best,

**Comment by devernay** [comment]
openfx-misc is GPLv2, so you can distribute the precompiled binaries under the conditions of GPLv2.

It must be downloaded separately from the main software, so that your software is not considered linked to openfx-misc (GPL is contaminated, so your program would become GPL as well).
Source code for openfx-misc must be available and downloadable as well (this is a legal obligation on your side, so you must provide the source that was used to produce the precompiled binaries).

**Comment by WindowsNT** [comment]
Thanks for your quick response, is it possible to download the binaries within my applications interface itself? Or has to be a browser?
